DROP DATABASE flight;
CREATE DATABASE flight;

USE flight;

CREATE TABLE flight
(
FL_DATE DATE,
OP_UNIQUE_CARRIER CHAR(2),
OP_CARRIER_FL_NUM VARCHAR(5),
ORIGIN_CITY_MARKET_ID CHAR(5),
DEST_CITY_MARKET_ID CHAR(5),
CRS_DEP_TIME TIME,
DEP_TIME TIME,
DEP_DELAY FLOAT,
ARR_TIME TIME,
ARR_DELAY FLOAT,
ARR_DELAY_NEW FLOAT,
CANCELLED FLOAT,
DISTANCE FLOAT
);

CREATE TABLE city
(
citymarketid CHAR(5),
city_name VARCHAR(20),
state CHAR(2),
markets INT,
cur_passengers INT,
cur_fare INT
);

CREATE TABLE airlines
(
name VARCHAR(50),
iata CHAR(2),
country VARCHAR(25)
);